apiVersion: v1
kind: Service
metadata:
  name: person-api-service-np
  labels:
    name: person-api-deploy
    app: person-api-app
spec:
  type: NodePort
  selector:
    app: person-api-app
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30070
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: person-api-app-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: person-api-app-1
  template:
    metadata:
      labels:
        app: person-api-app-1
    spec:
      containers:
        - name: person-api-container-1
          image: "710473750744.dkr.ecr.us-east-2.amazonaws.com/api_peson"
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: company-api-service-np
  labels:
    name: company-api-deploy
    app: company-api-app
spec:
  type: NodePort
  selector:
    app: company-api-app
  ports:
    - protocol: TCP
      port: 8081
      nodePort: 30071

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: company-api-app-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: company-api-app-2
  template:
    metadata:
      labels:
        app: company-api-app-2
    spec:
      containers:
        - name: company-api-container-2
          image: "710473750744.dkr.ecr.us-east-2.amazonaws.com/api_company"
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: company-api-service-np
  labels:
    name: company-api-deploy
    app: company-api-app
spec:
  type: NodePort
  selector:
    app: company-api-app
  ports:
    - protocol: TCP
      port: 8083
      nodePort: 30073
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: company-api-app-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: company-api-app-2
  template:
    metadata:
      labels:
        app: company-api-app-2
    spec:
      containers:
        - name: company-api-container-2
          image: "710473750744.dkr.ecr.us-east-2.amazonaws.com/api_company"
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: loan-api-service-np
  labels:
    name: loan-api-deploy
    app: loan-api-app
spec:
  type: NodePort
  selector:
    app: loan-api-app
  ports:
    - protocol: TCP
      port: 8084
      nodePort: 30074
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: loan-api-app-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loan-api-app-2
  template:
    metadata:
      labels:
        app: loan-api-app-2
    spec:
      containers:
        - name: loan-api-container-2
          image: "710473750744.dkr.ecr.us-east-2.amazonaws.com/api_loan"
          imagePullPolicy: Always
          ports:
            - containerPort: 8084
